referenceDocs:
  pagination: section
  showConsole: true
  colors:
    primary:
      main: '#1d1d21'
  theme:
    menu:
      backgroundColor: '#f5f5f6'
    typography:
      fontFamily: "ABC Whyte", Helvetica, Arial, sans-serif

lint:
  extends:
  - minimal