referenceDocs:
  pagination: section
  showConsole: true
  colors:
    primary:
      main: '#1d1d21'
  theme:
    menu:
      backgroundColor: '#f5f5f6'
  generateCodeSamples:
    languages:
      - lang: curl
        label: Oldschool cURL
      - lang: Python
      - lang: JavaScript

lint:
  extends:
  - minimal