openapi: 3.0.1
info:
  title: Inlinehooks API
  description: Inlinehooks API
  version: 1.0.0
paths:
  /api/v1/inlineHooks:
    get:
      tags:
      - InlineHook
      description: Success
      operationId: listInlineHooks
      parameters:
      - name: type
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHook'
      security:
      - api_token: []
    post:
      tags:
      - InlineHook
      description: Success
      operationId: createInlineHook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHook'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHook'
      security:
      - api_token: []
      x-okta-request-body-name: inlineHook
  /api/v1/inlineHooks/{inlineHookId}:
    get:
      tags:
      - InlineHook
      description: Gets an inline hook by ID
      operationId: getInlineHook
      parameters:
      - name: inlineHookId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHook'
      security:
      - api_token: []
    put:
      tags:
      - InlineHook
      description: Updates an inline hook by ID
      operationId: updateInlineHook
      parameters:
      - name: inlineHookId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHook'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHook'
      security:
      - api_token: []
      x-okta-request-body-name: inlineHook
    delete:
      tags:
      - InlineHook
      description: Deletes the Inline Hook matching the provided id. Once deleted,
        the Inline Hook is unrecoverable. As a safety precaution, only Inline Hooks
        with a status of INACTIVE are eligible for deletion.
      operationId: deleteInlineHook
      parameters:
      - name: inlineHookId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
          content: {}
      security:
      - api_token: []
  /api/v1/inlineHooks/{inlineHookId}/execute:
    post:
      tags:
      - InlineHook
      description: Executes the Inline Hook matching the provided inlineHookId using
        the request body as the input. This will send the provided data through the
        Channel and return a response if it matches the correct data contract. This
        execution endpoint should only be used for testing purposes.
      operationId: executeInlineHook
      parameters:
      - name: inlineHookId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHookPayload'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHookResponse'
      security:
      - api_token: []
      x-okta-request-body-name: payloadData
  /api/v1/inlineHooks/{inlineHookId}/lifecycle/activate:
    post:
      tags:
      - InlineHook
      description: Activates the Inline Hook matching the provided id
      operationId: activateInlineHook
      parameters:
      - name: inlineHookId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHook'
  /api/v1/inlineHooks/{inlineHookId}/lifecycle/deactivate:
    post:
      tags:
      - InlineHook
      description: Deactivates the Inline Hook matching the provided id
      operationId: deactivateInlineHook
      parameters:
      - name: inlineHookId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/InlineHook.yaml#/components/schemas/InlineHook'
components:
  securitySchemes:
    api_token:
      type: apiKey
      description: SSWS {API Token}
      name: Authorization
      in: header
