openapi: 3.0.1
info:
  title: Templates API
  description: Templates API
  version: 1.0.0
paths:
  /api/v1/templates/sms:
    get:
      tags:
      - Template
      summary: List SMS Templates
      description: Enumerates custom SMS templates in your organization. A subset
        of templates can be returned that match a template type.
      operationId: listSmsTemplates
      parameters:
      - name: templateType
        in: query
        schema:
          $ref: '../../components/Template.yaml#/components/schemas/SmsTemplateType'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../components/Template.yaml#/components/schemas/SmsTemplate'
      security:
      - api_token: []
    post:
      tags:
      - Template
      summary: Add SMS Template
      description: Adds a new custom SMS template to your organization.
      operationId: createSmsTemplate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../components/Template.yaml#/components/schemas/SmsTemplate'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/Template.yaml#/components/schemas/SmsTemplate'
      security:
      - api_token: []
      x-okta-request-body-name: smsTemplate
  /api/v1/templates/sms/{templateId}:
    get:
      tags:
      - Template
      summary: Get SMS Template
      description: Fetches a specific template by `id`
      operationId: getSmsTemplate
      parameters:
      - name: templateId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/Template.yaml#/components/schemas/SmsTemplate'
      security:
      - api_token: []
    put:
      tags:
      - Template
      summary: Update SMS Template
      description: Updates the SMS template.
      operationId: updateSmsTemplate
      parameters:
      - name: templateId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../components/Template.yaml#/components/schemas/SmsTemplate'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/Template.yaml#/components/schemas/SmsTemplate'
      security:
      - api_token: []
      x-okta-request-body-name: smsTemplate
    post:
      tags:
      - Template
      summary: Partial SMS Template Update
      description: 'Updates only some of the SMS template properties:'
      operationId: partialUpdateSmsTemplate
      parameters:
      - name: templateId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../components/Template.yaml#/components/schemas/SmsTemplate'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '../../components/Template.yaml#/components/schemas/SmsTemplate'
      security:
      - api_token: []
      x-okta-request-body-name: smsTemplate
    delete:
      tags:
      - Template
      summary: Remove SMS Template
      description: Removes an SMS template.
      operationId: deleteSmsTemplate
      parameters:
      - name: templateId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
          content: {}
      security:
      - api_token: []
components:
  securitySchemes:
    api_token:
      type: apiKey
      description: SSWS {API Token}
      name: Authorization
      in: header
