openapi: 3.0.1
info:
  title: Domain Components
  version: 1.0.0
paths: {}
components:
  schemas:
    DNSRecord:
      type: object
      properties:
        expiration:
          type: string
        fqdn:
          type: string
        recordType:
          $ref: '#/components/schemas/DNSRecordType'
        values:
          type: array
          items:
            type: string
      x-okta-tags:
      - Domain
    DNSRecordType:
      type: string
      enum:
      - TXT
      - CNAME
      x-okta-tags:
      - Domain
    Domain:
      type: object
      properties:
        certificateSourceType:
          $ref: '#/components/schemas/DomainCertificateSourceType'
        dnsRecords:
          type: array
          items:
            $ref: '#/components/schemas/DNSRecord'
        domain:
          type: string
        id:
          type: string
        publicCertificate:
          $ref: '#/components/schemas/DomainCertificateMetadata'
        validationStatus:
          $ref: '#/components/schemas/DomainValidationStatus'
      x-okta-tags:
      - Domain
    DomainCertificate:
      type: object
      properties:
        certificate:
          type: string
        certificateChain:
          type: string
        privateKey:
          type: string
        type:
          $ref: '#/components/schemas/DomainCertificateType'
      x-okta-operations:
      - alias: createCertificate
        arguments:
        - dest: certificate
          self: true
        operationId: createCertificate
      x-okta-tags:
      - Domain
    DomainCertificateMetadata:
      type: object
      properties:
        expiration:
          type: string
        fingerprint:
          type: string
        subject:
          type: string
      x-okta-tags:
      - Domain
    DomainCertificateSourceType:
      type: string
      enum:
      - MANUAL
      x-okta-tags:
      - Domain
    DomainCertificateType:
      type: string
      enum:
      - PEM
      x-okta-tags:
      - Domain
    DomainLinks:
      type: object
      properties:
        certificate:
          type: object
          properties: {}
        self:
          type: object
          properties: {}
        verify:
          type: object
          properties: {}
      x-okta-tags:
      - Domain
    DomainListResponse:
      type: object
      properties:
        domains:
          type: array
          items:
            $ref: '#/components/schemas/DomainResponse'
      x-okta-tags:
      - Domain
    DomainResponse:
      type: object
      properties:
        certificateSourceType:
          type: string
          enum:
          - MANUAL
        dnsRecords:
          type: array
          items:
            $ref: '#/components/schemas/DNSRecord'
        domain:
          type: string
        id:
          type: string
        _links:
          $ref: '#/components/schemas/DomainLinks'
        publicCertificate:
          $ref: '#/components/schemas/DomainCertificateMetadata'
        validationStatus:
          type: string
          enum:
          - NOT_STARTED
          - IN_PROGRESS
          - VERIFIED
          - COMPLETED
      x-okta-tags:
      - Domain
    DomainValidationStatus:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - VERIFIED
      - COMPLETED
      x-okta-tags:
      - Domain
