openapi: 3.0.1
info:
  title: Event Hook Components
  version: 1.0.0
paths: {}
components:
  schemas:
    EventHook:
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            type: object
            properties: {}
          readOnly: true
        channel:
          $ref: '#/components/schemas/EventHookChannel'
        created:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
        events:
          $ref: '#/components/schemas/EventSubscriptions'
        id:
          type: string
          readOnly: true
        lastUpdated:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
        status:
          type: string
          enum:
          - ACTIVE
          - INACTIVE
        verificationStatus:
          type: string
          enum:
          - UNVERIFIED
          - VERIFIED
      x-okta-crud:
      - alias: create
        arguments:
        - dest: eventHook
          self: true
        operationId: createEventHook
      - alias: read
        arguments: []
        operationId: getEventHook
      - alias: update
        arguments:
        - dest: eventHookId
          src: id
        - dest: eventHook
          self: true
        operationId: updateEventHook
      - alias: delete
        arguments:
        - dest: eventHookId
          src: id
        operationId: deleteEventHook
      x-okta-operations:
      - alias: activate
        arguments:
        - dest: eventHookId
          src: id
        operationId: activateEventHook
      - alias: deactivate
        arguments:
        - dest: eventHookId
          src: id
        operationId: deactivateEventHook
      - alias: verify
        arguments:
        - dest: eventHookId
          src: id
        operationId: verifyEventHook
      x-okta-tags:
      - EventHook
    EventHookChannel:
      type: object
      properties:
        config:
          $ref: '#/components/schemas/EventHookChannelConfig'
        type:
          type: string
          enum:
          - HTTP
        version:
          type: string
      x-okta-tags:
      - EventHook
    EventHookChannelConfig:
      type: object
      properties:
        authScheme:
          $ref: '#/components/schemas/EventHookChannelConfigAuthScheme'
        headers:
          type: array
          items:
            $ref: '#/components/schemas/EventHookChannelConfigHeader'
        uri:
          type: string
      x-okta-tags:
      - EventHook
    EventHookChannelConfigAuthScheme:
      type: object
      properties:
        key:
          type: string
        type:
          $ref: '#/components/schemas/EventHookChannelConfigAuthSchemeType'
        value:
          type: string
      x-okta-tags:
      - EventHook
    EventHookChannelConfigAuthSchemeType:
      type: string
      enum:
      - HEADER
      x-okta-tags:
      - EventHook
    EventHookChannelConfigHeader:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      x-okta-tags:
      - EventHook
    EventSubscriptions:
      type: object
      properties:
        items:
          type: array
          items:
            type: string
        type:
          type: string
          enum:
          - EVENT_TYPE
          - FLOW_EVENT
      discriminator:
        propertyName: type
      x-okta-tags:
      - EventHook
