openapi: 3.0.1
info:
  title: Feature Components
  version: 1.0.0
paths: {}
components:
  schemas:
    Feature:
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            type: object
            properties: {}
          readOnly: true
        description:
          type: string
        id:
          type: string
          readOnly: true
        name:
          type: string
        stage:
          $ref: '#/components/schemas/FeatureStage'
        status:
          $ref: './Common.yaml#/components/schemas/EnabledStatus'
        type:
          $ref: '#/components/schemas/FeatureType'
      x-okta-crud:
      - alias: read
        arguments: []
        operationId: getFeature
      x-okta-operations:
      - alias: updateLifecycle
        arguments:
        - dest: featureId
          src: id
        operationId: updateFeatureLifecycle
      - alias: getDependents
        arguments:
        - dest: featureId
          src: id
        operationId: listFeatureDependents
      - alias: getDependencies
        arguments:
        - dest: featureId
          src: id
        operationId: listFeatureDependencies
      x-okta-tags:
      - Feature
    FeatureStage:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/FeatureStageState'
        value:
          $ref: '#/components/schemas/FeatureStageValue'
      x-okta-tags:
      - Feature
    FeatureStageState:
      type: string
      enum:
      - OPEN
      - CLOSED
      x-okta-tags:
      - Feature
    FeatureStageValue:
      type: string
      enum:
      - EA
      - BETA
      x-okta-tags:
      - Feature
    FeatureType:
      type: string
      enum:
      - self-service
      x-okta-tags:
      - Feature
