openapi: 3.0.1
info:
  title: Identity Provider Components
  version: 1.0.0
paths: {}
components:
  schemas:
    IdentityProvider:
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            type: object
            properties: {}
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        id:
          type: string
          readOnly: true
        issuerMode:
          type: string
          enum:
          - ORG_URL
          - CUSTOM_URL_DOMAIN
        lastUpdated:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
        policy:
          $ref: './Policy.yaml#/components/schemas/IdentityProviderPolicy'
        protocol:
          $ref: '#/components/schemas/Protocol'
        status:
          type: string
          enum:
          - ACTIVE
          - INACTIVE
        type:
          type: string
          x-okta-known-values:
          - SAML2
          - GOOGLE
          - FACEBOOK
          - LINKEDIN
          - MICROSOFT
          - OIDC
          - OKTA
          - IWA
          - AgentlessDSSO
          - X509
      x-okta-crud:
      - alias: create
        arguments:
        - dest: idpTrust
          self: true
        operationId: createIdentityProvider
      - alias: read
        arguments: []
        operationId: getIdentityProvider
      - alias: update
        arguments:
        - dest: idpId
          src: id
        - dest: idpTrust
          self: true
        operationId: updateIdentityProvider
      - alias: delete
        arguments:
        - dest: idpId
          src: id
        operationId: deleteIdentityProvider
      x-okta-operations:
      - alias: listSigningCsrs
        arguments:
        - dest: idpId
          src: id
        operationId: listCsrsForIdentityProvider
      - alias: generateCsr
        arguments:
        - dest: idpId
          src: id
        operationId: generateCsrForIdentityProvider
      - alias: deleteSigningCsr
        arguments:
        - dest: idpId
          src: id
        operationId: revokeCsrForIdentityProvider
      - alias: getSigningCsr
        arguments:
        - dest: idpId
          src: id
        operationId: getCsrForIdentityProvider
      - alias: listSigningKeys
        arguments:
        - dest: idpId
          src: id
        operationId: listIdentityProviderSigningKeys
      - alias: generateSigningKey
        arguments:
        - dest: idpId
          src: id
        operationId: generateIdentityProviderSigningKey
      - alias: getSigningKey
        arguments:
        - dest: idpId
          src: id
        operationId: getIdentityProviderSigningKey
      - alias: cloneKey
        arguments:
        - dest: idpId
          src: id
        operationId: cloneIdentityProviderKey
      - alias: activate
        arguments:
        - dest: idpId
          src: id
        operationId: activateIdentityProvider
      - alias: deactivate
        arguments:
        - dest: idpId
          src: id
        operationId: deactivateIdentityProvider
      - alias: listUsers
        arguments:
        - dest: idpId
          src: id
        operationId: listIdentityProviderApplicationUsers
      - alias: unlinkUser
        arguments:
        - dest: idpId
          src: id
        operationId: unlinkUserFromIdentityProvider
      - alias: getUser
        arguments:
        - dest: idpId
          src: id
        operationId: getIdentityProviderApplicationUser
      - alias: linkUser
        arguments:
        - dest: idpId
          src: id
        operationId: linkUserToIdentityProvider
      - alias: listSocialAuthTokens
        arguments:
        - dest: idpId
          src: id
        operationId: listSocialAuthTokens
      x-okta-tags:
      - IdentityProvider
    IdentityProviderApplicationUser:
      type: object
      properties:
        _embedded:
          type: object
          additionalProperties:
            type: object
            properties: {}
          readOnly: true
        _links:
          type: object
          additionalProperties:
            type: object
            properties: {}
          readOnly: true
        created:
          type: string
        externalId:
          type: string
        id:
          type: string
          readOnly: true
        lastUpdated:
          type: string
        profile:
          type: object
          additionalProperties:
            type: object
            properties: {}
      x-okta-tags:
      - IdentityProvider
    IdentityProviderCredentials:
      type: object
      properties:
        client:
          $ref: '#/components/schemas/IdentityProviderCredentialsClient'
        signing:
          $ref: '#/components/schemas/IdentityProviderCredentialsSigning'
        trust:
          $ref: '#/components/schemas/IdentityProviderCredentialsTrust'
      x-okta-tags:
      - IdentityProvider
    IdentityProviderCredentialsClient:
      type: object
      properties:
        client_id:
          type: string
        client_secret:
          type: string
      x-okta-tags:
      - IdentityProvider
    IdentityProviderCredentialsSigning:
      type: object
      properties:
        kid:
          type: string
      x-okta-tags:
      - IdentityProvider
    IdentityProviderCredentialsTrust:
      type: object
      properties:
        audience:
          type: string
        issuer:
          type: string
        kid:
          type: string
        revocation:
          type: string
          enum:
          - CRL
          - DELTA_CRL
          - OCSP
        revocationCacheLifetime:
          type: integer
      x-okta-tags:
      - IdentityProvider
    Protocol:
      type: object
      properties:
        algorithms:
          $ref: '#/components/schemas/ProtocolAlgorithms'
        credentials:
          $ref: '#/components/schemas/IdentityProviderCredentials'
        endpoints:
          $ref: '#/components/schemas/ProtocolEndpoints'
        issuer:
          $ref: '#/components/schemas/ProtocolEndpoint'
        relayState:
          $ref: '#/components/schemas/ProtocolRelayState'
        scopes:
          type: array
          items:
            type: string
        settings:
          $ref: '#/components/schemas/ProtocolSettings'
        type:
          type: string
          enum:
          - SAML2
          - OIDC
          - OAUTH2
          - MTLS
      x-okta-tags:
      - IdentityProvider
    ProtocolAlgorithmType:
      type: object
      properties:
        signature:
          $ref: '#/components/schemas/ProtocolAlgorithmTypeSignature'
      x-okta-tags:
      - IdentityProvider
    ProtocolAlgorithmTypeSignature:
      type: object
      properties:
        algorithm:
          type: string
        scope:
          type: string
          enum:
          - RESPONSE
          - TOKEN
          - ANY
          - REQUEST
          - NONE
      x-okta-tags:
      - IdentityProvider
    ProtocolAlgorithms:
      type: object
      properties:
        request:
          $ref: '#/components/schemas/ProtocolAlgorithmType'
        response:
          $ref: '#/components/schemas/ProtocolAlgorithmType'
      x-okta-tags:
      - IdentityProvider
    ProtocolEndpoint:
      type: object
      properties:
        binding:
          type: string
          enum:
          - HTTP-POST
          - HTTP-REDIRECT
        destination:
          type: string
        type:
          type: string
          enum:
          - INSTANCE
          - ORG
        url:
          type: string
      x-okta-tags:
      - IdentityProvider
    ProtocolEndpoints:
      type: object
      properties:
        acs:
          $ref: '#/components/schemas/ProtocolEndpoint'
        authorization:
          $ref: '#/components/schemas/ProtocolEndpoint'
        jwks:
          $ref: '#/components/schemas/ProtocolEndpoint'
        metadata:
          $ref: '#/components/schemas/ProtocolEndpoint'
        slo:
          $ref: '#/components/schemas/ProtocolEndpoint'
        sso:
          $ref: '#/components/schemas/ProtocolEndpoint'
        token:
          $ref: '#/components/schemas/ProtocolEndpoint'
        userInfo:
          $ref: '#/components/schemas/ProtocolEndpoint'
      x-okta-tags:
      - IdentityProvider
    ProtocolRelayState:
      type: object
      properties:
        format:
          $ref: '#/components/schemas/ProtocolRelayStateFormat'
      x-okta-tags:
      - IdentityProvider
    ProtocolRelayStateFormat:
      type: string
      enum:
      - OPAQUE
      - FROM_URL
      x-okta-tags:
      - IdentityProvider
    ProtocolSettings:
      type: object
      properties:
        nameFormat:
          type: string
      x-okta-tags:
      - IdentityProvider
    Provisioning:
      type: object
      properties:
        action:
          type: string
          enum:
          - AUTO
          - CALLOUT
          - DISABLED
        conditions:
          $ref: '#/components/schemas/ProvisioningConditions'
        groups:
          $ref: '#/components/schemas/ProvisioningGroups'
        profileMaster:
          type: boolean
      x-okta-tags:
      - IdentityProvider
    ProvisioningConditions:
      type: object
      properties:
        deprovisioned:
          $ref: '#/components/schemas/ProvisioningDeprovisionedCondition'
        suspended:
          $ref: '#/components/schemas/ProvisioningSuspendedCondition'
      x-okta-tags:
      - IdentityProvider
    ProvisioningDeprovisionedCondition:
      type: object
      properties:
        action:
          type: string
          enum:
          - NONE
          - REACTIVATE
      x-okta-tags:
      - IdentityProvider
    ProvisioningGroups:
      type: object
      properties:
        action:
          type: string
          enum:
          - NONE
          - APPEND
          - SYNC
          - ASSIGN
        assignments:
          type: array
          items:
            type: string
        filter:
          type: array
          items:
            type: string
        sourceAttributeName:
          type: string
      x-okta-tags:
      - IdentityProvider
    ProvisioningSuspendedCondition:
      type: object
      properties:
        action:
          type: string
          enum:
          - NONE
          - UNSUSPEND
      x-okta-tags:
      - IdentityProvider
    SocialAuthToken:
      type: object
      properties:
        expiresAt:
          type: string
          format: date-time
          readOnly: true
        id:
          type: string
          readOnly: true
        scopes:
          type: array
          items:
            type: string
        token:
          type: string
        tokenAuthScheme:
          type: string
        tokenType:
          type: string
          enum:
          - ACCESS
          - REFRESH
      x-okta-tags:
      - IdentityProvider
