openapi: 3.0.1
info:
  title: Inline Hook Components
  version: 1.0.0
paths: {}
components:
  schemas:
    InlineHook:
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            type: object
            properties: {}
          readOnly: true
        channel:
          $ref: '#/components/schemas/InlineHookChannel'
        created:
          type: string
          format: date-time
          readOnly: true
        id:
          type: string
          readOnly: true
        lastUpdated:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
        status:
          $ref: '#/components/schemas/InlineHookStatus'
        type:
          $ref: '#/components/schemas/InlineHookType'
        version:
          type: string
      x-okta-crud:
      - alias: create
        arguments:
        - dest: inlineHook
          self: true
        operationId: createInlineHook
      - alias: read
        arguments: []
        operationId: getInlineHook
      - alias: update
        arguments:
        - dest: inlineHookId
          src: id
        - dest: inlineHook
          self: true
        operationId: updateInlineHook
      - alias: delete
        arguments:
        - dest: inlineHookId
          src: id
        operationId: deleteInlineHook
      x-okta-operations:
      - alias: activate
        arguments:
        - dest: inlineHookId
          src: id
        operationId: activateInlineHook
      - alias: deactivate
        arguments:
        - dest: inlineHookId
          src: id
        operationId: deactivateInlineHook
      - alias: execute
        arguments:
        - dest: inlineHookId
          src: id
        operationId: executeInlineHook
      x-okta-tags:
      - InlineHook
    InlineHookChannel:
      type: object
      properties:
        config:
          $ref: '#/components/schemas/InlineHookChannelConfig'
        type:
          type: string
          enum:
          - HTTP
        version:
          type: string
      x-okta-tags:
      - InlineHook
    InlineHookChannelConfig:
      type: object
      properties:
        authScheme:
          $ref: '#/components/schemas/InlineHookChannelConfigAuthScheme'
        headers:
          type: array
          items:
            $ref: '#/components/schemas/InlineHookChannelConfigHeaders'
        uri:
          type: string
        method:
          type: string
      x-okta-tags:
      - InlineHook
    InlineHookChannelConfigAuthScheme:
      type: object
      properties:
        key:
          type: string
        type:
          type: string
        value:
          type: string
      x-okta-tags:
      - InlineHook
    InlineHookChannelConfigHeaders:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      x-okta-tags:
      - InlineHook
    InlineHookPayload:
      type: object
      x-okta-tags:
      - InlineHook
      x-okta-extensible: true
    InlineHookResponse:
      type: object
      properties:
        commands:
          type: array
          items:
            $ref: '#/components/schemas/InlineHookResponseCommands'
      x-okta-tags:
      - InlineHook
    InlineHookResponseCommandValue:
      type: object
      properties:
        op:
          type: string
        path:
          type: string
        value:
          type: string
      x-okta-tags:
      - InlineHook
    InlineHookResponseCommands:
      type: object
      properties:
        type:
          type: string
        value:
          type: array
          items:
            $ref: '#/components/schemas/InlineHookResponseCommandValue'
      x-okta-tags:
      - InlineHook
    InlineHookStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      x-okta-tags:
      - InlineHook
    InlineHookType:
      type: string
      enum:
      - com.okta.oauth2.tokens.transform
      - com.okta.import.transform
      - com.okta.saml.tokens.transform
      - com.okta.user.pre-registration
      - com.okta.user.credential.password.import
      x-okta-tags:
      - InlineHook
