openapi: 3.0.1
info:
  title: User Type Components
  version: 1.0.0
paths: {}
components:
  schemas:
    UserType:
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            type: object
            properties: {}
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        default:
          type: boolean
          readOnly: true
        description:
          type: string
        displayName:
          type: string
        id:
          type: string
        lastUpdated:
          type: string
          format: date-time
          readOnly: true
        lastUpdatedBy:
          type: string
          readOnly: true
        name:
          type: string
      x-okta-crud:
      - alias: create
        arguments:
        - dest: userType
          self: true
        operationId: createUserType
      - alias: update
        arguments:
        - dest: typeId
          src: id
        - dest: userType
          self: true
        operationId: updateUserType
      - alias: read
        arguments:
        - dest: typeId
          src: id
        operationId: getUserType
      - alias: delete
        arguments:
        - dest: typeId
          src: id
        operationId: deleteUserType
      x-okta-operations:
      - alias: replaceUserType
        arguments:
        - dest: roleId
          src: id
        operationId: replaceUserType
      x-okta-tags:
      - UserType
